# version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - redis
      - db
    command: >
      sh -c "python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: feedback_reports
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./app:/app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
    depends_on:
      - redis
      - db

  flower:
    build: .
    command: celery -A core flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data: