# Generated by Django 5.2 on 2025-05-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlreport',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdfreport',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
